#!/bin/bash
# One-time Snellius environment setup: create venv, install nodis + rpy2, run unit tests.
# R module names are read from .env — never hardcoded here.
# Usage: bash scripts/snellius_setup.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

source "${SCRIPT_DIR}/_load_env.sh"
_load_dotenv "${PROJECT_ROOT}/.env"

for var in SNELLIUS_HOST SNELLIUS_USER SNELLIUS_PASSWORD SNELLIUS_PORT \
           SNELLIUS_REMOTE_DIR SNELLIUS_MODULE_ENV SNELLIUS_MODULE_R; do
    if [[ -z "${!var:-}" ]]; then
        echo "ERROR: ${var} is not set in .env" >&2; exit 1
    fi
done

export SSHPASS="${SNELLIUS_PASSWORD}"

sshpass -e ssh -p "${SNELLIUS_PORT}" \
    -o StrictHostKeyChecking=accept-new \
    "${SNELLIUS_USER}@${SNELLIUS_HOST}" \
    "set -e

     echo '--- Writing snellius_modules.sh ---'
     cat > \$HOME/NODIS/snellius_modules.sh <<'MODULES'
# Auto-generated by scripts/snellius_setup.sh — do not edit manually.
# Source this file to load the Snellius software environment.
module load ${SNELLIUS_MODULE_ENV}
module load ${SNELLIUS_MODULE_R}
MODULES

     echo '--- Creating venv with python3.11 (skipped if exists) ---'
     [[ -d \$HOME/NODIS/.venv ]] || python3.11 -m venv \$HOME/NODIS/.venv

     echo '--- Activating venv ---'
     source \$HOME/NODIS/.venv/bin/activate

     echo '--- Installing nodis[dev] ---'
     pip install --quiet -e \"\$HOME/NODIS/.[dev]\"

     echo '--- Loading R modules ---'
     source \$HOME/NODIS/snellius_modules.sh

     echo '--- Installing rpy2 ---'
     pip install --quiet rpy2

     echo '--- Running unit tests ---'
     pytest \$HOME/NODIS/tests/unit/ -v"

unset SSHPASS
